# generated by datamodel-codegen:
#   filename:  change-data-log-json-schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import AwareDatetime, ConfigDict, Field

from ssb_poc_statlog_model.statlog_base_model import StatlogBaseModel


class ChangeEvent(StrEnum):
    """How the event was triggered: Automatically changed (A), Manually changed (M), Manually approved with no change (MNC), Not reviewed (NOT)."""

    A = "A"
    M = "M"
    MNC = "MNC"
    NOT = "NOT"


class ChangeEventReason(StrEnum):
    """Reason for change or approval: Other source (OTHER_SOURCE), Statistical review (REVIEW), Information from the data provider/registry owner (OWNER), Small/marginal unit (MARGINAL_UNIT), Data duplicate (DUPLICATE), Other reason (OTHER)."""

    OTHER_SOURCE = "OTHER_SOURCE"
    REVIEW = "REVIEW"
    OWNER = "OWNER"
    MARGINAL_UNIT = "MARGINAL_UNIT"
    DUPLICATE = "DUPLICATE"
    OTHER = "OTHER"


class DataChangeType(StrEnum):
    """Data change type: Updated value (UPD), created new unit/row (NEW), or deleted unit/row (DEL)."""

    NEW = "NEW"
    UPD = "UPD"
    DEL = "DEL"


class ChangeDetails(StatlogBaseModel):
    """Detailed information about the change. Either a unit-id, old and new value if one row (unit) was affected, or number of rows affected if the process changed multiple rows (units)."""

    model_config = ConfigDict(
        extra="forbid",
    )
    detail_type: Annotated[
        Literal["rows"], Field(description="Discriminator for change_details variant")
    ] = "rows"
    rows_affected: Annotated[
        int,
        Field(
            description="Number of rows affected if the process changed multiple rows (units)."
        ),
    ]
    variable_name: Annotated[
        str,
        Field(
            description="The variable name (or element-path) that contains data changes."
        ),
    ]


class UnitIdItem(StatlogBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    unit_id_variable: Annotated[
        str,
        Field(
            description="The unit-id variable name, e.g. 'fnr', 'pers_id', 'reg_nr' or 'komm_nr'."
        ),
    ]
    unit_id_value: Annotated[
        str, Field(description="The unit-id value, e.g. '311280nnnnn' or '123456789'.")
    ]


class OldValueItem(StatlogBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    variable_name: str
    value: str


class NewValueItem(StatlogBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    variable_name: str
    value: str


class ChangeDetails1(StatlogBaseModel):
    """Detailed information about the change. Either a unit-id, old and new value if one row (unit) was affected, or number of rows affected if the process changed multiple rows (units)."""

    model_config = ConfigDict(
        extra="forbid",
    )
    detail_type: Annotated[
        Literal["unit"], Field(description="Discriminator for change_details variant")
    ] = "unit"
    unit_id: Annotated[
        list[UnitIdItem],
        Field(
            description="One or more unit-identifier variables and values (primary key) if one row (unit) was affected, eg. 'fnr'='311280nnnnn' and 'orgnr'='123456789'."
        ),
    ]
    old_value: Annotated[
        list[OldValueItem] | None,
        Field(
            description="Old value(s). If delete (data_change_type = DEL) - log all deleted variable-values from the deleted data row/record, eg. 'income'='1000', 'address'='Street 123', ..."
        ),
    ] = None
    new_value: Annotated[
        list[NewValueItem] | None,
        Field(
            description="New value(s). If insert (data_change_type = INS) - log all inserted variable-values in the data row/record, eg. 'income'='1000', 'address'='Street 123', ..."
        ),
    ] = None


class DatasetMember(StatlogBaseModel):
    """An object belonging to a partitioned dataset, relative to its root."""

    model_config = ConfigDict(
        extra="forbid",
    )
    path: Annotated[
        str,
        Field(
            description="Nonempty relative object path without traversal, URI scheme, or a leading slash.",
            pattern="^[^/:?#\\\\][^:?#\\\\]*$",
        ),
    ]
    generation: Annotated[
        str,
        Field(
            description="Exact GCS generation of this member, as a decimal string.",
            pattern="^[0-9]+$",
        ),
    ]


class DatasetReference(StatlogBaseModel):
    """A GCS file with a generation, or a partitioned dataset root with inline member identities."""

    model_config = ConfigDict(
        extra="forbid",
    )
    path: Annotated[
        str,
        Field(
            description="Canonical GCS object path or partitioned Parquet root, not a mounted alias.",
            pattern="^gs://[a-z0-9][a-z0-9._-]*[a-z0-9]/[^?#]+$",
        ),
    ]
    generation: Annotated[
        str | None,
        Field(
            description="GCS generation for a single file; null or omitted for partitioned roots. Unknown for a single file means incomplete provenance.",
            pattern="^[0-9]+$",
        ),
    ] = None
    members: Annotated[
        list[DatasetMember] | None,
        Field(
            description="Complete inline partition member identities with relative paths. No separate manifest file.",
            min_length=1,
        ),
    ] = None


class ChangeDataLog(StatlogBaseModel):
    """Data model for data change log in a statistical production process."""

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Annotated[
        Literal["3.0.0"], Field(description="Version of this schema.")
    ] = "3.0.0"
    event_id: Annotated[
        str | None,
        Field(
            description="Stable identifier of this persisted change event.",
            min_length=1,
        ),
    ] = None
    segment_id: Annotated[
        str | None,
        Field(
            description="Identifier linking this change to its transformation's lineage.",
            min_length=1,
        ),
    ] = None
    recorded_at: Annotated[
        AwareDatetime | None,
        Field(
            description="Timezone-aware instant when this event was recorded, distinct from change_datetime."
        ),
    ] = None
    gsbpm_code: Annotated[
        str | None,
        Field(
            description="Optional GSBPM code from Klass classification 933.",
            pattern="^[1-8](?:\\.[0-9]+)*$",
        ),
    ] = None
    producer_metadata: Annotated[
        dict[str, Any] | None,
        Field(
            description="Team-defined JSON-compatible production details; cannot override named fields."
        ),
    ] = None
    statistics_name: Annotated[
        str, Field(description="Statistics shortname or statistics product name")
    ]
    data_source: Annotated[
        list[DatasetReference],
        Field(
            description="Input GCS paths with generations or inline partition members used before changing data."
        ),
    ]
    data_target: Annotated[
        str,
        Field(description="Target dataset filepath (eg. GCS-path to a parquet file)."),
    ]
    data_period: Annotated[
        str,
        Field(
            description="Data period for changed data - eg. a year, quarter, month, day (date), ..."
        ),
    ]
    change_event: Annotated[
        ChangeEvent,
        Field(
            description="How the event was triggered: Automatically changed (A), Manually changed (M), Manually approved with no change (MNC), Not reviewed (NOT)."
        ),
    ]
    change_event_reason: Annotated[
        ChangeEventReason | None,
        Field(
            description="Reason for change or approval: Other source (OTHER_SOURCE), Statistical review (REVIEW), Information from the data provider/registry owner (OWNER), Small/marginal unit (MARGINAL_UNIT), Data duplicate (DUPLICATE), Other reason (OTHER)."
        ),
    ] = None
    change_datetime: Annotated[
        AwareDatetime,
        Field(description="Timestamp (date and time, ISO 8601) of an event or change"),
    ]
    changed_by: Annotated[
        str,
        Field(
            description="If manually (M): user name of the person who triggered an event; if automatically (A) name of method, function and/or process."
        ),
    ]
    data_change_type: Annotated[
        DataChangeType | None,
        Field(
            description="Data change type: Updated value (UPD), created new unit/row (NEW), or deleted unit/row (DEL)."
        ),
    ] = None
    change_comment: Annotated[str | None, Field(description="Change comment")] = None
    change_details: Annotated[
        ChangeDetails | ChangeDetails1,
        Field(
            description="Detailed information about the change. Either a unit-id, old and new value if one row (unit) was affected, or number of rows affected if the process changed multiple rows (units).",
            discriminator="detail_type",
        ),
    ]
