# generated by datamodel-codegen:
#   filename:  change-data-log-json-schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class ChangeEvent(str, Enum):
    A = "A"
    M = "M"
    MNC = "MNC"
    NOT = "NOT"


class ChangeEventReason(str, Enum):
    OTHER_SOURCE = "OTHER_SOURCE"
    REVIEW = "REVIEW"
    OWNER = "OWNER"
    MARGINAL_UNIT = "MARGINAL_UNIT"
    DUPLICATE = "DUPLICATE"
    OTHER = "OTHER"


class DataChangeType(str, Enum):
    NEW = "NEW"
    UPD = "UPD"
    DEL = "DEL"


class ChangeDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    detail_type: Literal["rows"] = Field(
        "rows", description="Discriminator for change_details variant"
    )
    rows_affected: int = Field(
        ...,
        description="Number of rows affected if the process changed multiple rows (units).",
    )
    variable_name: str | None = Field(
        None,
        description="The variable name (or element-path) that contains data changes.",
    )


class UnitIdItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    unit_id_variable: str = Field(
        ...,
        description="The unit-id variable name, e.g. 'fnr', 'pers_id', 'reg_nr' or 'komm_nr'.",
    )
    unit_id_value: str = Field(
        ..., description="The unit-id value, e.g. '311280nnnnn' or '123456789'."
    )


class OldValueItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    variable_name: str
    value: str


class NewValueItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    variable_name: str
    value: str


class ChangeDetails1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    detail_type: Literal["unit"] = Field(
        "unit", description="Discriminator for change_details variant"
    )
    unit_id: list[UnitIdItem] = Field(
        ...,
        description="One or more unit-identifier variables and values (primary key) if one row (unit) was affected, eg. 'fnr'='311280nnnnn' and 'orgnr'='123456789'.",
    )
    old_value: list[OldValueItem] | None = Field(
        None,
        description="Old value(s). If delete (data_change_type = DEL) - log all deleted variable-values from the deleted data row/record, eg. 'income'='1000', 'adress'='Street 123', ...",
    )
    new_value: list[NewValueItem] | None = Field(
        None,
        description="New value(s). If insert (data_change_type = INS) - log all inserted variable-values in the data row/record, eg. 'income'='1000', 'adress'='Street 123', ...",
    )


class ChangeDataLog(BaseModel):
    statistics_name: str = Field(
        ..., description="Statistics shortname or statistics product name"
    )
    data_source: list[str] = Field(
        ...,
        description="Reference or filepath to one or more input datasets used as data source before changing data.",
    )
    data_target: str = Field(
        ..., description="Target dataset filepath (eg. GCS-path to a parquet file)."
    )
    data_period: str = Field(
        ...,
        description="Data period for changed data - eg. a year, quarter, month, day (date), ...",
    )
    variable_name: str | None = Field(
        None,
        description="The variable name (or element-path) that contains data changes.",
    )
    change_event: ChangeEvent = Field(
        ...,
        description="How the event was triggered: Automatically changed (A), Manually changed (M), Manually approved with no change (MNC), Not reviewed (NOT)",
    )
    change_event_reason: ChangeEventReason | None = Field(
        None,
        description="Reason for change or approval: Other source (OTHER_SOURCE), Statistical review (REVIEW), Information from the data provider/registry owner (OWNER), Small/marginal unit (MARGINAL_UNIT), Data duplicate (DUPLICATE), Other reason (OTHER)",
    )
    change_datetime: AwareDatetime = Field(
        ..., description="Timestamp (date and time, ISO 8601) of an event or change"
    )
    changed_by: str = Field(
        ...,
        description="If manually (M): user name of the person who triggered an event; if automatically (A) name of method, function and/or process.",
    )
    data_change_type: DataChangeType | None = Field(
        None,
        description="Data change type: Updated value (UPD), created new unit/row (NEW), or deleted unit/row (DEL)",
    )
    change_comment: str | None = Field(None, description="Change comment")
    change_details: ChangeDetails | ChangeDetails1 = Field(
        ...,
        description="Detailed information about the change. Either a unit-id, old and new value if one row (unit) was affected, or number of rows affected if the process changed multiple rows (units).",
        discriminator="detail_type",
    )
