# generated by datamodel-codegen:
#   filename:  environment-metadata-json-schema.json

from __future__ import annotations

from pydantic import AwareDatetime, Field

from ssb_poc_statlog_model.statlog_base_model import StatlogBaseModel


class EnvironmentMetadata(StatlogBaseModel):
    """Common metadata captured from the environment."""

    log_created_at: AwareDatetime = Field(
        ...,
        description="Timestamp (date and time, ISO 8601) when the log entry was created.",
    )
    username: str = Field(
        ..., description="Username of the actor or service creating the log entry."
    )
    dapla_environment: str = Field(..., description="Dapla environment identifier.")
    dapla_service: str = Field(..., description="Dapla service identifier.")
    dapla_region: str = Field(..., description="Dapla region identifier.")
    git_repo_name: str = Field(..., description="Git repository name.")
    git_commit_sha: str = Field(
        ..., description="SHA of the last available git commit."
    )
