# generated by datamodel-codegen:
#   filename:  lineage-json-schema.json

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import AwareDatetime, ConfigDict, Field

from ssb_poc_statlog_model.statlog_base_model import StatlogBaseModel


class DatasetMember(StatlogBaseModel):
    """An object belonging to a partitioned dataset, relative to its root."""

    model_config = ConfigDict(
        extra="forbid",
    )
    path: Annotated[
        str,
        Field(
            description="Nonempty relative object path without traversal, URI scheme, or a leading slash.",
            pattern="^[^/:?#\\\\][^:?#\\\\]*$",
        ),
    ]
    generation: Annotated[
        str,
        Field(
            description="Exact GCS generation of this member, as a decimal string.",
            pattern="^[0-9]+$",
        ),
    ]


class DatasetReference(StatlogBaseModel):
    """A GCS file with a generation, or a partitioned dataset root with inline member identities."""

    model_config = ConfigDict(
        extra="forbid",
    )
    path: Annotated[
        str,
        Field(
            description="Canonical GCS object path or partitioned Parquet root, not a mounted alias.",
            pattern="^gs://[a-z0-9][a-z0-9._-]*[a-z0-9]/[^?#]+$",
        ),
    ]
    generation: Annotated[
        str | None,
        Field(
            description="GCS generation for a single file; null or omitted for partitioned roots. Unknown for a single file means incomplete provenance.",
            pattern="^[0-9]+$",
        ),
    ] = None
    members: Annotated[
        list[DatasetMember] | None,
        Field(
            description="Complete inline partition member identities with relative paths. No separate manifest file.",
            min_length=1,
        ),
    ] = None


class Lineage(StatlogBaseModel):
    """Data model for data lineage in a statistical production process."""

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Annotated[
        Literal["3.0.0"], Field(description="Version of this schema.")
    ] = "3.0.0"
    data_source: Annotated[
        list[DatasetReference],
        Field(
            description="Input GCS datasets and the generations consumed by the transformation."
        ),
    ]
    data_target: Annotated[
        list[DatasetReference],
        Field(
            description="Successfully saved output GCS datasets and their finalized generations."
        ),
    ]
    step: Annotated[
        str | None,
        Field(
            description="A string describing at which step in the process the log is for."
        ),
    ] = None
    event_id: Annotated[
        str | None,
        Field(
            description="Stable identifier of this persisted lineage event.",
            min_length=1,
        ),
    ] = None
    segment_id: Annotated[
        str | None,
        Field(
            description="Identifier shared with quality and change events for this transformation.",
            min_length=1,
        ),
    ] = None
    recorded_at: Annotated[
        AwareDatetime | None,
        Field(
            description="Timezone-aware instant when this event was recorded, distinct from execution time."
        ),
    ] = None
    git_commit_hash: Annotated[
        str | None,
        Field(description="Git commit of the code used for this transformation."),
    ] = None
    git_repository: Annotated[
        str | None,
        Field(
            description="Repository name or sanitized URI containing the executed code and its configuration.",
            min_length=1,
        ),
    ] = None
    git_dirty: Annotated[
        bool | None,
        Field(
            description="Whether staged, unstaged, or untracked non-ignored changes existed. Null means unknown."
        ),
    ] = None
    image_name: Annotated[
        str | None,
        Field(
            description="Complete container image reference from IMAGE_NAME, including its tag."
        ),
    ] = None
    dapla_environment: Annotated[
        str | None,
        Field(
            description="Platform environment from DAPLA_ENVIRONMENT, not dataset publication status."
        ),
    ] = None
    dapla_region: Annotated[
        str | None,
        Field(
            description="Platform context from DAPLA_REGION; DAPLA_LAB is not a geographic region."
        ),
    ] = None
    dapla_service: Annotated[
        str | None, Field(description="Execution service from DAPLA_SERVICE.")
    ] = None
    dapla_team_google_project_id: Annotated[
        str | None,
        Field(description="Google project context from DAPLA_TEAM_GOOGLE_PROJECT_ID."),
    ] = None
    execution_started_at: Annotated[
        AwareDatetime | None,
        Field(
            description="Timezone-aware execution start instant, preferably expressed in UTC."
        ),
    ] = None
    execution_finished_at: Annotated[
        AwareDatetime | None,
        Field(
            description="Timezone-aware execution finish instant, preferably expressed in UTC."
        ),
    ] = None
    timezone: Annotated[
        str | None,
        Field(
            description="Effective process timezone, preferably an IANA name. Null means unknown."
        ),
    ] = None
    utc_offset_seconds: Annotated[
        int | None,
        Field(
            description="Effective UTC offset in seconds at execution start; does not replace timezone rules.",
            gt=-86400,
            lt=86400,
        ),
    ] = None
    configured_tz: Annotated[
        str | None,
        Field(
            description="Configured TZ environment variable, not proof of the effective process timezone."
        ),
    ] = None
    gsbpm_code: Annotated[
        str | None,
        Field(
            description="Optional GSBPM code from Klass classification 933; membership is checked by the logger.",
            pattern="^[1-8](?:\\.[0-9]+)*$",
        ),
    ] = None
    producer_metadata: Annotated[
        dict[str, Any] | None,
        Field(
            description="Team-defined JSON-compatible production details; cannot override named fields."
        ),
    ] = None
