# generated by datamodel-codegen:
#   filename:  output-file-log-json-schema.json

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, Field

from ssb_poc_statlog_model.statlog_base_model import StatlogBaseModel


class StepLog(StatlogBaseModel):
    step_log_sha256: str = Field(..., description="SHA-256 of the referenced step log.")
    step_log_path: str | None = Field(
        None, description="Path or URI to the referenced step log file."
    )


class HashAlgorithm(str, Enum):
    """Hash algorithm used for *_sha256 fields."""

    sha256 = "sha256"


class EnvironmentMetadata(StatlogBaseModel):
    """Common metadata captured from the environment."""

    log_created_at: AwareDatetime = Field(
        ...,
        description="Timestamp (date and time, ISO 8601) when the log entry was created.",
    )
    username: str = Field(
        ..., description="Username of the actor or service creating the log entry."
    )
    dapla_environment: str = Field(..., description="Dapla environment identifier.")
    dapla_service: str = Field(..., description="Dapla service identifier.")
    dapla_region: str = Field(..., description="Dapla region identifier.")
    git_repo_name: str = Field(..., description="Git repository name.")
    git_commit_sha: str = Field(
        ..., description="SHA of the last available git commit."
    )


class OutputFileLog(EnvironmentMetadata):
    """Log schema for produced output files in a statistical production workflow."""

    output_file_path: str = Field(
        ..., description="Path or URI to the produced output file."
    )
    output_file_size_bytes: int = Field(
        ..., description="Size of the produced output file in bytes."
    )
    output_file_last_modified: AwareDatetime = Field(
        ...,
        description="Last modified timestamp (date and time, ISO 8601) of the produced output file.",
    )
    input_file_paths: list[str] | None = Field(
        None,
        description="Path or URI to one or more input files used to create the output file.",
    )
    step_logs: list[StepLog] = Field(
        ...,
        description="Ordered list of step-log references that produced the output file.",
    )
    log_sha256: str | None = Field(
        None, description="SHA-256 checksum of this log entry for immutability."
    )
    hash_algorithm: HashAlgorithm = Field(
        ..., description="Hash algorithm used for *_sha256 fields."
    )
