# generated by datamodel-codegen:
#   filename:  quality-control-description-json-schema.json

from __future__ import annotations

from enum import Enum

from pydantic import Field

from ssb_poc_statlog_model.statlog_base_model import StatlogBaseModel


class QualityControlType(str, Enum):
    """Quality control type: hard (H), soft (S), informative (I)."""

    H = "H"
    S = "S"
    I = "I"


class Variable(StatlogBaseModel):
    variable_description: str | None = None


class QualityControlDescription(StatlogBaseModel):
    """Model for description of quality controls used in a statistical production."""

    quality_control_id: str = Field(..., description="A unique quality control ID")
    quality_control_description: str = Field(
        ..., description="Quality control description"
    )
    quality_control_type: QualityControlType = Field(
        ..., description="Quality control type: hard (H), soft (S), informative (I)."
    )
    variables: list[Variable] = Field(
        ...,
        description="A description of which variables must be included in the quality control.",
    )
