# generated by datamodel-codegen:
#   filename:  release-log-json-schema.json

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, Field

from ssb_poc_statlog_model.statlog_base_model import StatlogBaseModel


class OutputFileLog(StatlogBaseModel):
    output_file_log_sha256: str = Field(
        ..., description="SHA-256 of the referenced output-file log."
    )
    output_file_log_path: str | None = Field(
        None, description="Path or URI to the referenced output-file log file."
    )


class HashAlgorithm(str, Enum):
    """Hash algorithm used for *_sha256 fields."""

    sha256 = "sha256"


class EnvironmentMetadata(StatlogBaseModel):
    """Common metadata captured from the environment."""

    log_created_at: AwareDatetime = Field(
        ...,
        description="Timestamp (date and time, ISO 8601) when the log entry was created.",
    )
    username: str = Field(
        ..., description="Username of the actor or service creating the log entry."
    )
    dapla_environment: str = Field(..., description="Dapla environment identifier.")
    dapla_service: str = Field(..., description="Dapla service identifier.")
    dapla_region: str = Field(..., description="Dapla region identifier.")
    git_repo_name: str = Field(..., description="Git repository name.")
    git_commit_sha: str = Field(
        ..., description="SHA of the last available git commit."
    )


class ReleaseLog(EnvironmentMetadata):
    """Log schema for releases of produced output files."""

    release_comment: str = Field(
        ..., description="Reason or context for why the release exists."
    )
    publication_datetime: AwareDatetime = Field(
        ...,
        description="Publication time (date and time, ISO 8601) when the output becomes public.",
    )
    output_file_logs: list[OutputFileLog] = Field(
        ..., description="References to output-file logs included in the release."
    )
    log_sha256: str | None = Field(
        None, description="SHA-256 checksum of this log entry for immutability."
    )
    hash_algorithm: HashAlgorithm = Field(
        ..., description="Hash algorithm used for *_sha256 fields."
    )
