# generated by datamodel-codegen:
#   filename:  release-json-schema.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import Field

from ssb_poc_statlog_model.statlog_base_model import StatlogBaseModel


class Release(StatlogBaseModel):
    """Data model for a release in a statistical production process."""

    schema_version: Annotated[
        Literal["1.0.0"], Field(description="Version of this schema.")
    ] = "1.0.0"
    dapla_team: Annotated[
        str, Field(description="Name of the dapla team that produced the release.")
    ]
    statistics_name: Annotated[
        str, Field(description="Statistics shortname or statistics product name")
    ]
    git_tag: Annotated[str, Field(description="Git tag for the release.")]
    git_commit_hash: Annotated[
        str, Field(description="Git commit hash for the release.")
    ]
    data_source: Annotated[
        list[str],
        Field(
            description="Reference or filepath to one or more datasets in the final data state (utdata or klargjorte-data) used as data source for the release."
        ),
    ]
    daplalab_image: Annotated[
        str | None,
        Field(
            description="The tag of the Daplalab container image that produced the release."
        ),
    ] = None
