# generated by datamodel-codegen:
#   filename:  step-log-json-schema.json

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, Field

from ssb_poc_statlog_model.statlog_base_model import StatlogBaseModel


class QualityControlLog(StatlogBaseModel):
    log_sha256: str = Field(
        ..., description="SHA-256 of the referenced quality control log."
    )
    log_path: str | None = Field(
        None, description="Path or URI to the referenced quality control log file."
    )


class ChangeDataLog(StatlogBaseModel):
    log_sha256: str = Field(
        ..., description="SHA-256 of the referenced change-data log."
    )
    log_path: str | None = Field(
        None, description="Path or URI to the referenced change-data log file."
    )


class HashAlgorithm(str, Enum):
    """Hash algorithm used for *_sha256 fields."""

    sha256 = "sha256"


class EnvironmentMetadata(StatlogBaseModel):
    """Common metadata captured from the environment."""

    log_created_at: AwareDatetime = Field(
        ...,
        description="Timestamp (date and time, ISO 8601) when the log entry was created.",
    )
    username: str = Field(
        ..., description="Username of the actor or service creating the log entry."
    )
    dapla_environment: str = Field(..., description="Dapla environment identifier.")
    dapla_service: str = Field(..., description="Dapla service identifier.")
    dapla_region: str = Field(..., description="Dapla region identifier.")
    git_repo_name: str = Field(..., description="Git repository name.")
    git_commit_sha: str = Field(
        ..., description="SHA of the last available git commit."
    )


class StepLog(EnvironmentMetadata):
    """Log schema for process steps in a statistical production workflow."""

    step_name: str = Field(..., description="Name or identifier of the process step.")
    step_description: str | None = Field(
        None, description="Short description of the process step."
    )
    input_file_paths: list[str] = Field(
        ..., description="Path or URI to one or more input files for the step."
    )
    quality_control_logs: list[QualityControlLog] | None = Field(
        None, description="References to quality control logs produced for the step."
    )
    change_data_logs: list[ChangeDataLog] | None = Field(
        None, description="References to change-data logs produced for the step."
    )
    step_log_sha256: str | None = Field(
        None, description="SHA-256 checksum of this step log entry for immutability."
    )
    hash_algorithm: HashAlgorithm = Field(
        ..., description="Hash algorithm used for *_sha256 fields."
    )
